#!/bin/bash

###########################################################################
virtualhost="A REMPLI"
server_name="A REMPLI"
document_root="A REMPLIR"
###########################################################################

echo "----------------------------------------------------"
echo "Installation de Nginx Reverse Proxy"
echo "----------------------------------------------------"
read -p "Appuyez sur une touche pour continuer..."
apt-get update && apt-get upgrade
apt-get install nginx libapache2-mod-rpaf

echo "upstream backend_apache{
    server 127.0.0.1:8080;
}

server {
    listen    80;
    server_name    ${server_name};
    root ${document_root}
    
    location / {
	include proxy_params;
	proxy_pass http://backend_apache;
    }
}" > /etc/nginx/sites-available/${virtualhost}.conf

ln -s /etc/nginx/sites-available/${virtualhost}.conf /etc/nginx/sites-enabled/${virtualhost}.conf
systemctl reload nginx
