#!/bin/bash

###########################################################################
virtualhost="A REMPLIR"
server_name="A REMPLIR"
document_root="A REMPLIR"
email="A REMPLIR"
###########################################################################

# NE PAS TOUCHER A PARTIR D'ICI !!!!!!!!
echo "----------------------------------------------------"
echo "Installation de Lamp + SSL"
echo "----------------------------------------------------"
read -p "Appuyez sur une touche pour continuer..."
apt-get update && apt-get upgrade
apt-get install apache2 php7.3-fpm php7.3-mysql php7.3-gd php7.3-imap php7.3-curl php7.3-ldap php7.3-xmlrpc php-apcu php7.3-mbstring php7.3-xml php-cas mariadb-server-10.3

a2enmod proxy_fcgi setenvif
a2enconf php7.3-fpm
a2dismod php7.3 mpm_prefork
a2enmod mpm_event
a2enmod ssl
systemctl restart apache2

mkdir /var/www/html/${document_root}

openssl req -new -x509 -days 3650 -nodes -newkey rsa:4096 -out /etc/ssl/certs/https.pem -keyout /etc/ssl/private/https.pem

echo "<VirtualHost 127.0.0.1:8080>
    ServerName ${server_name}
    ServerAlias ${server_name}
    ServerAdmin webmaster@${server_name}
	
    DocumentRoot /var/www/html/${document_root}
    ProxyPassMatch ^/(.*\.php(/.*)?)$ unix:/run/php/php7.3-fpm.sock|fcgi://localhost/var/www/html/${document_root}

    CustomLog ${APACHE_LOG_DIR}/www.${document_root}-access.log combined
    ErrorLog ${APACHE_LOG_DIR}/www.${document_root}-error.log
    
#    <IfModule mod_rewrite.c>
#        RewriteEngine On
#        RewriteCond %{HTTPS} !=on
#        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
#    </IfModule>
	
    <Directory /var/www/html/${document_root}>
        Options All
        AllowOverride None
    </Directory>
	</VirtualHost>
	
#	<IfModule mod_ssl.c>
#		<VirtualHost 127.0.0.1:443>
#			SSLEngine On
#			SSLCertificateFile     /etc/ssl/certs/https.pem
#			SSLCertificateKeyFile   /etc/ssl/private/https.pem
#		</VirtualHost>
#	</IfModule>" > /etc/apache2/sites-available/01-${virtualhost}.conf

a2ensite ${virtualhost}.conf
systemctl reload apache2

mysql_secure_installation
