#!/bin/bash

###########################################################################
virtualhost="cybermetrik"
server_name="www.cybermetrik.com"
document_root="cybermetrik"
email="cybermetrik@gmail.com"
ip="192.168.42.10"
###########################################################################

# NE PAS TOUCHER A PARTIR D'ICI !!!!!!!!
echo "----------------------------------------------------"
echo "Installation de Lamp + SSL"
echo "----------------------------------------------------"
read -p "Appuyez sur une touche pour continuer..."
apt-get update && apt-get upgrade
apt-get install apache2 php7.3-fpm php7.3-mysql php7.3-gd php7.3-imap php7.3-curl php7.3-ldap php7.3-xmlrpc php-apcu php7.3-mbstring php7.3-xml php-cas mariadb-server-10.3

a2enmod proxy_fcgi setenvif
a2enconf php7.3-fpm
a2dismod php7.3 mpm_prefork
a2enmod mpm_event
a2enmod ssl
a2enmod rewrite
systemctl restart apache2

echo "Listen 127.0.0.1:8080

<IfModule ssl_module>
        Listen 127.0.0.1:443
</IfModule>

<IfModule mod_gnutls.c>
	Listen 127.0.0.1:443
</IfModule>" > /etc/apache2/ports.conf

mkdir /var/www/html/${document_root}

openssl req -new -x509 -days 3650 -nodes -newkey rsa:4096 -out /etc/ssl/certs/https.pem -keyout /etc/ssl/private/https.pem

echo "<VirtualHost *:8080>
          ServerName ${server_name}
          ServerAlias ${server_name}
          ServerAdmin ${email}
	
          DocumentRoot /var/www/html/${document_root}
          ProxyPassMatch ^/(.*\.php(/.*)?)$ unix:/run/php/php7.3-fpm.sock|fcgi://localhost/var/www/html/${document_root}

         CustomLog ${APACHE_LOG_DIR}/www.${document_root}-access.log combined
         ErrorLog ${APACHE_LOG_DIR}/www.${document_root}-error.log
  
	 <IfModule mod_rewrite.c>
		RewriteEngine On
		RewriteCond %{HTTPS} !=on
	 	RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
	 </IfModule>
	
         <Directory /var/www/html/${document_root}>
              Options All
              AllowOverride None
         </Directory>
     </VirtualHost>" > /etc/apache2/sites-available/http-${virtualhost}.conf

echo "<IfModule mod_ssl.c>
          <VirtualHost *:443>
          	ServerName ${server_name}
          	ServerAlias ${server_name}
	  	ServerAdmin {email}
	
	        DocumentRoot /var/www/html/${document_root}
		ProxyPassMatch ^/(.*\.php(/.*)?)$ unix:/run/php/php7.3-fpm.sock|fcgi://localhost/var/www/html/${document_root}
		
         	CustomLog ${APACHE_LOG_DIR}/www.${document_root}-access.log combined
         	ErrorLog ${APACHE_LOG_DIR}/www.${document_root}-error.log
		
		SSLEngine On
		SSLCertificateFile     /etc/ssl/certs/https.pem
		SSLCertificateKeyFile   /etc/ssl/private/https.pem
		
	    	<Directory /var/www/html/${document_root}>
              		Options All
              		AllowOverride None
	        </Directory>
	   </VirtualHost>
      </IfModule>" > /etc/apache2/sites-available/https-${virtualhost}.conf
      
a2ensite http-${virtualhost}.conf
a2ensite https-${virtualhost}.conf

systemctl reload apache2

mysql_secure_installation
