#!/bin/bash

###########################################################################
version_NagiosCore="4.4.5"                
version_NagiosPlugin="2.3.3"  

pseudo="A REMPLIR"
password="A REMPLIR"
###########################################################################

# NE PAS TOUCHER A PARTIR D'ICI !!!!!!!!

apt-get install libxml-libxml-perl libnet-snmp-perl libperl-dev libnumber-format-perl libconfig-inifiles-perl libdatetime-perl libnet-dns-perl libpng-dev libjpeg-dev libgd-dev gcc make autoconf libc6 unzip
useradd nagios
groupadd nagcmd
usermod -a -G nagcmd nagios
usermod -a -G nagcmd www-data
mkdir /home/nagios/downloads
cd /home/nagios/downloads

wget https://assets.nagios.com/downloads/nagioscore/releases/nagios-${version_NagiosCore}.tar.gz
tar -zxvf nagios-${version_NagiosCore}.tar.gz
rm -rf nagios-${version_NagiosCore}.tar.gz
cd nagios-${version_NagiosCore}
./configure --with-httpd-conf=/etc/apache2/sites-enabled --with-command-group=nagcmd
make all
make install
make install-daemoninit
make install-commandmode
make install-config
make install-webconf

a2enmod rewrite
a2enmod cgi

htpasswd -cb /usr/local/nagios/etc/htpasswd.users ${pseudo} ${password}

chown -R nagios:nagcmd /usr/local/nagios

systemctl restart apache2
systemctl start nagios

cd /home/nagios/downloads
wget https://nagios-plugins.org/download/nagios-plugins-${version_NagiosPlugin}.tar.gz
tar -zxvf nagios-plugins-${version_NagiosPlugin}.tar.gz
rm -rf nagios-plugins-${version_NagiosPlugin}.tar.gz
cd nagios-plugins-${version_NagiosPlugin}/

./configure --with-nagios-user=nagios --with-nagios-group=nagcmd 
make
make install

echo "alias testNagios='/usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg'" >> /home/nagios/.bashrc
echo "nagios ALL=NOPASSWD:/bin/systemctl restart nagios" >> /etc/sudoers
echo "alias restartNagios='sudo systemctl restart nagios'" >> /home/nagios/.bashrc
