#!/bin/bash

###########################################################################
database="zabbix"
username="zabbix"                
password="12345"
###########################################################################

echo "----------------------------------------------------"
echo "Installation et Configuration de Zabbix"
echo "----------------------------------------------------"
read -p "Appuyez sur une touche pour continuer..."

apt-get install zabbix-server-mysql zabbix-frontend-php zabbix-agent snmpd

mysql -u root -p -e "create database ${database} character set utf8"
mysql -u root -p -e "grant all privileges on ${database}.* to ${username}@localhost identified by '${password}'"
mysql -u root -p -e "flush privileges"

gzip -d /usr/share/zabbix-server-mysql/schema.sql.gz | mysql -u zabbix -pzabbix zabbix < schema.sql
gzip -d /usr/share/zabbix-server-mysql/images.sql.gz | mysql -u zabbix -pzabbix zabbix < images.sql
gzip -d /usr/share/zabbix-server-mysql/data.sql.gz | mysql -u zabbix -pzabbix zabbix < data.sql

echo "<IfModule mod_alias.c>
    Alias /zabbix /usr/share/zabbix
</IfModule>


<Directory /usr/share/zabbix>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride None
        Order allow,deny
        allow from all
</Directory>" > /etc/apache2/conf-available/zabbix-server.conf

a2enconf zabbix-server
systemctl restart zabbix-server
