#!/bin/bash

###########################################################################
version_gpli="9.5.0-rc1"
fusion="9.4+2.4"
GPLI_database="A REMPLIR"
GPLI_user="A REMPLIR"
GPLI_password="A REMPLIR"

mysql_server="A REMPLIR"
password_server="A REMPLIR"
###########################################################################

# NE PAS TOUCHER A PARTIR D'ICI !!!!!!!!
echo "----------------------------------------------------"
echo "Mise à Jour du Serveur Linux"
echo "----------------------------------------------------"
read -p "Appuyez sur une touche pour continuer..."
apt-get update && apt-get upgrade

echo "----------------------------------------------------"
echo "Installation du Serveur GPLI"
echo "----------------------------------------------------"
read -p "Appuyez sur une touche pour continuer..."
apt-get install apcupsd

mysql -u${mysql_server} -p${password_server} -e "create database ${GPLI_database} character set utf8"
mysql -u${mysql_server} -p${password_server} -e "grant all privileges on ${GPLI_database}.* to '${GPLI_user}'@'localhost' identified by '${GPLI_password}'"
mysql -u${mysql_server} -p${password_server} -e "flush privileges"

cd /usr/src/
wget https://github.com/glpi-project/glpi/releases/download/${version_gpli}/glpi-${version_gpli}.tgz
tar -xvzf glpi-${version_gpli}.tgz -C /var/www/html
chown -R www-data /var/www/html/glpi/

cd /var/www/html/glpi/plugins
git clone https://github.com/pluginsGLPI/mreporting.git
