#!/bin/bash 
 
# Réinitialise les règles
sudo iptables -t filter -F 
sudo iptables -t filter -X 
 
# Bloque tout le trafic
sudo iptables -t filter -P INPUT DROP 
sudo iptables -t filter -P FORWARD DROP 
sudo iptables -t filter -P OUTPUT DROP 
 
# Autorise les connexions déjà établies et localhost
sudo iptables -A INPUT -m state --state ESTABLISHED -j ACCEPT 
sudo iptables -A OUTPUT -m state --state ESTABLISHED -j ACCEPT 
sudo iptables -t filter -A INPUT -i lo -j ACCEPT 
sudo iptables -t filter -A OUTPUT -o lo -j ACCEPT 
 
# Autorise le Ping
sudo iptables -t filter -A INPUT -p icmp -j ACCEPT 
sudo iptables -t filter -A OUTPUT -p icmp -j ACCEPT 

# Bloque les deny de services (tcp, udp et icmp)
sudo iptables -A FORWARD -p tcp --syn -m limit --limit 1/second -j ACCEPT
sudo iptables -A FORWARD -p udp -m limit --limit 1/second -j ACCEPT
sudo iptables -A FORWARD -p icmp --icmp-type echo-request -m limit --limit 1/second -j ACCEPT

# Autorise FTP
sudo iptables -t filter -A INPUT -p tcp --dport 21 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p tcp --dport 21 -j ACCEPT

# Autorise SSH
sudo iptables -t filter -A INPUT -p tcp --dport 22 -j ACCEPT 
sudo iptables -t filter -A OUTPUT -p tcp --dport 22 -j ACCEPT 

# Autorise Samba
sudo iptables -t filter -A INPUT -p tcp --dport 445 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p tcp --dport 445 -j ACCEPT

# Autorise bind9
sudo iptables -t filter -A INPUT -p tcp --dport 53 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p tcp --dport 53 -j ACCEPT
sudo iptables -t filter -A INPUT -p udp --dport 53 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p udp --dport 53 -j ACCEPT

# Autorise Nginx (Reverse Proxy)
sudo iptables -t filter -A INPUT -p tcp --dport 80 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p tcp --dport 80 -j ACCEPT

# Autorise Apache2
sudo iptables -t filter -A INPUT -p tcp --dport 8080 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p tcp --dport 8080 -j ACCEPT

# Autorise HTTPS
sudo iptables -t filter -A INPUT -p tcp --dport 443 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p tcp --dport 443 -j ACCEPT

# Autorise Mysql
sudo iptables -t filter -A INPUT -p tcp --dport 3306 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p tcp --dport 3306 -j ACCEPT

# Autorise Webmin
sudo iptables -t filter -A INPUT -p tcp --dport 10000 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p tcp --dport 10000 -j ACCEPT
