#!/bin/bash

nagios_version="4.4.5"
naggios_plugin_version="2.2.1"

username_webpanel="admin"
password_webpanel="admin"

apt-get install apache2 php php-gd php-imap php-curl php-mcrypt
apt-get install libxml-libxml-perl libnet-snmp-perl libperl-dev libnumber-format-perl libconfig-inifiles-perl libdatetime-perl libnet-dns-perl
apt-get install libpng-dev libjpeg-dev libgd-dev
apt-get install gcc make autoconf libc6 unzip

useradd nagios
groupadd nagcmd
usermod -a -G nagcmd nagios
usermod -a -G nagcmd www-data

mkdir /home/nagios/downloads
cd /home/nagios/downloads
wget https://assets.nagios.com/downloads/nagioscore/releases/nagios-${nagios_version}.tar.gz
tar -zxvf nagios--${nagios_version}.tar.gz
rm -rf nagios--${nagios_version}.tar.gz
cd nagios--${nagios_version}

./configure --with-httpd-conf=/etc/apache2/sites-enabled --with-command-group=nagcmd
make all
make install
make install-daemoninit
make install-commandmode
make install-config
make install-webconf

a2enmod rewrite
a2enmod cgi
htpasswd -cb /usr/local/nagios/etc/htpasswd.users ${username_webpanel} ${password_webpanel}
chown -R nagios:nagcmd /usr/local/nagios
systemctl restart apache2
systemctl start nagios

cd /home/nagios/downloads
wget https://nagios-plugins.org/download/nagios-plugins-${nagios_plugin_version}.tar.gz
tar -zxvf nagios-plugins-${nagios_plugin_version}.tar.gz
rm -rf nagios-plugins-${nagios_plugin_version}.tar.gz
cd nagios-plugins-${nagios_plugin_version}/

./configure --with-nagios-user=nagios --with-nagios-group=nagcmd 
make
make install

echo "alias testNagios='/usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg'" >> /home/nagios/.bashrc
echo "nagios ALL=NOPASSWD:/bin/systemctl restart nagios" >> /etc/sudoers
echo "alias restartNagios='sudo systemctl restart nagios'" >> /home/nagios/.bashrc
