#!/bin/bash

###########################################################################
domaine="www.mon-domaine.com"                
root="/var/www/html/mon_dossier"
email="webmaster@mon-domaine.com"
###########################################################################

echo "----------------------------------------------------"
echo "Téléchargement et installation de certificat SSL"
echo "----------------------------------------------------"
read -p "Appuyez sur une touche pour continuer..."

cd ../
wget https://dl.eff.org/certbot-auto
chmod a+x certbot-auto

./certbot-auto
./certbot-auto certonly --webroot --webroot-path ${root} --domain ${domaine} --email ${email}

crontab < <(crontab -l ; echo "00 00 01 /3 * ./certbot-auto renew --rsa-key-size 4096 --force-renewal")
